### ISSUE TITLE
Can't log in: outh2 KeyError

### ISSUE THREAD

**Issue by melianmiko** [lazeroffmichael/ticktick-py#20]
Some time ago it works, but now I can't log in.
Script wasn't modified, login and password are valid, API key too.

![изображение](https://user-images.githubusercontent.com/67851274/147400619-80d60d91-6b80-4f18-9689-f12a2b559724.png)

**Comment by melianmiko** [comment]
![изображение](https://user-images.githubusercontent.com/67851274/147400639-0ab84b17-db1b-4e9c-ba55-b090e506b20b.png)

**Comment by lazeroffmichael** [comment]
Hello!

I am assuming that you already set your redirect URL in the TickTick developer dashboard to be **https://melianmiko.ru**

When you accept permissions for your app to make changes to the account, it should redirect you to the **https://melianmiko.ru** URL with some added parameters - this is the URL you need to enter when it asks for where you are redirected to. 

For example, here is the URL that I am redirected to when I register a new app: **http://127.0.0.1:8080/?code=mtmoDK&state=None** where my specified URL is **http://127.0.0.1:8080**

The URL you are redirected to should have `code` and `state` present in it, I hope this made sense!

**Comment by melianmiko** [comment]
Wooops, I tried to log in from SSH session. I forgot how to do this =)
But it also don't work, now I got another error:
![изображение](https://user-images.githubusercontent.com/67851274/147431346-9e2d73b0-5c2b-4ad9-b5bd-624f167608a4.png)

**Comment by melianmiko** [comment]
Maybe something is changed in TickTick API? Few weeks ago this script works fine...

**Comment by lazeroffmichael** [comment]
I am getting a similar error so it does look like something changed on their end - I will work on a fix. Thank you for trying! I am going to close this issue and make a new one.
