### ISSUE TITLE
I want to say Thank you.

### ISSUE THREAD

**Issue by foreverlong** [lazeroffmichael/ticktick-py#32]
Thank you for this project. As you now, TickTick in China is Dida365. In auto platform like zapier, they only have TickTick. Dida365 is not in there. By your project, I change "ticktick.com" to "dida365.com" and it worked! Now I can make the sync between Notion and China's TickTick. I truly appreciate for your project. Thank you. I wish you can have good day.  : )
P.s. Sorry for my bad English.

**Comment by lazeroffmichael** [comment]
I am glad you have found value from it!
