### ISSUE TITLE
I successfully adapt it for dida365!

### ISSUE THREAD

**Issue by MrSnake0208** [lazeroffmichael/ticktick-py#41]
The reason why changing ticktick.com to dida365.com directly does not work for the TickTick China version is that dida365 requires headers and there are authentication issues. It is necessary to use base64 encryption for client id and secret. After consulting with official personnel, I made adjustments to the code:
1. Added dida365 options for users to decide whether or not to use dida365.
2. Modified the way of obtaining access token from dida365.
As a beginner, the formatting may be a bit messy, so you can format it uniformly after testing.

**Comment by C0rn3j** [comment]
I don't think this issue is necessary since you already opened a PR with the same comment and #6 exists.

https://github.com/lazeroffmichael/ticktick-py/pull/40

Side note, Base64 is encoding, not encryption.
